# config/packages/api_platform.yaml
api_platform:
  swagger:
    # The active versions of OpenAPI to be exported or used in the swagger_ui. The first value is the default.
    versions: [3]
    api_keys:
      JWT:
        name: Authorization
        type: header
